### ISSUE TITLE
Keyboard doesn't works

### ISSUE THREAD

**Issue by jmcerrejon** [maccasoft/raspberry-pi#1]
I press a key (SPACE for example) and then the Keyboard does not respond. I tried with Spanish & USA USB keyboard on a Raspberry Pi B.

**Comment by maccasoft** [comment]
The project is now using the new USPi USB library that should have a better compatibility with keyboards. Check it out.

**Comment by jmcerrejon** [comment]
If keyboard is pluged directly to the Pi, works perfectly, but with the beyboard connected through a USB HUB, doesn't work. 

Anyway, good job!

**Comment by maccasoft** [comment]
Yes, HUBs are not yet supported.
